### ISSUE TITLE
cannot open file

### ISSUE THREAD

**Issue by Yakumo-Yukari** [enthus1ast/nimja#111]
src/
│   ├── controllers/
│   │   └── user_controller.nim
│   ├── views/
│   │   ├── user/
│   │   │   ├── register.nimja
│   │   │   └── login.nimja
│   │   └── layout.nimja
│   ├── database/
│   │   └── connection.nim
│   └── App.nim

err
`Error: cannot open file: views\user\register.nimja`

```
  else:
    try:
      #resp tmplf("views/user/register.nimja")
      #resp tmplf("../views" / "user/register.nimja", baseDir = getScriptDir())
    except:
      resp """<div class="alert alert-danger">err</div>"""
```

How can I use the template path correctly?
